[project]
name = "orchestrator"
version = "0.1.0"
description = ""
authors = [
    {name = "Giuseppe Monitillo",email = "113453755+GMon11@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic (>=2.13.5,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "pandas (>=2.2.0,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]

[project.scripts]
orchestrator = "orchestrator.__main__:run"
test = "utils.test_runner:run"

[tool.poetry]
packages = [
    {include = "orchestrator", from = "src"},
    {include = "classes", from = "src"},
    {include = "utils", from = "src"}
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
